# -*- coding: utf-8 -*-
"""CSE-522_Computational_Project_Probability_Dist_Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bsTXOacBUnB5xeOtzJi_PVFdDitfF_6u
"""

import numpy as np
import math
import pandas as pd
import matplotlib.pyplot as plt
import seaborn
from scipy.stats import binom

#-----Read Radius of Gyration Data---------
high_den_rog = pd.read_csv('High_Density_ROG_wFalse.txt', sep=" ", header=None)
low_den_rog = pd.read_csv('Low_Density_ROG_wFalse.txt', sep=" ", header=None)

#Takes only the Equilibrium data
equi = 600

eq_high_den_rog = high_den_rog[equi:]
eq_low_den_rog = low_den_rog[equi:]

#----Plotting Distribution Functions-----

ax = plt.subplot(1)
ax=seaborn.distplot(eq_high_den_rog,hist=False,label='High Density Proteins')
ax.set_xscale('log')
ax.set(xlabel='Radius of Gyration (nm)',ylabel='P($R_g$)')
ax.legend()
ax.figure.savefig("Prob_Dist_High_Density.pdf")
plt.show()

ax = plt.subplot(2)
ax=seaborn.distplot(eq_low_den_rog,hist=False,label='Low Density Proteins')
ax.set(xlabel='Radius of Gyration (nm)',ylabel='P($R_g$)')
ax.legend()
ax.figure.savefig("Prob_Dist_Low_Density.pdf")

plt.show()